### ISSUE TITLE
Jest in monorepos

### ISSUE THREAD

**Issue by entropitor** [nvim-neotest/neotest-jest#60] opened 2023-04-20 08:42 UTC
https://github.com/nvim-neotest/neotest-jest/commit/0c0dad7799e1a90fc17363241696cee0bda60c45 broken jest detection in monorepos. We have a monorepo but not every package has jest in its package json. It is however installed in the root and so neotest-jest was working just fine before this commit. 

Can this commit be reverted?

**Comment by HugoArts** [comment] 2023-04-25 21:04
I am experiencing a similar issue because we use create-react-app. Our package.json doesn't contain the `jest` dependency directly but we use it indirectly through the dependency on `react-scripts`. Running `npm install --save-dev jest` does fix it, but doesn't seem ideal.

**Comment by mikaoelitiana** [comment] 2023-05-19 16:15
@HugoArts , I have the same issue. I have created this PR to fix that https://github.com/nvim-neotest/neotest-jest/pull/63

**Comment by guivazcabral** [comment] 2023-06-30 08:38
I've proposed a wider fix for this issue with https://github.com/nvim-neotest/neotest-jest/pull/64

**Comment by mikaoelitiana** [comment] 2023-07-28 10:02
@entropitor #64 has been merge and the issue is now fixed. Can you confirm it's OK on your project and close the issue if it's all fine?

**Closed** 2023-08-08 11:27 UTC

**Comment by men232** [comment] 2024-04-30 22:38
I guess it is better to find nearest package.json via lspconfig

```lua
          require "neotest-jest" {
            jestCommand = "npm test --",
            jestConfigFile = "custom.jest.config.ts",
            env = { CI = true },
            cwd = function(path)
              local root_path = require("lspconfig").util.root_pattern "package.json"(path)
              return root_path or vim.fn.getcwd()
            end,
          },
```
